<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
    <meta name="renderer" content="webkit|ie-comp|ie-stand">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta http-equiv="Cache-Control" content="no-siteapp" />
    <meta name="keywords" content="scclui框架">
    <meta name="description" content="scclui为轻量级的网站后台管理系统模版。">
    <title>首页</title>

    <link rel="stylesheet" href="/public/css/admin/sccl.css">
    <link rel="stylesheet" type="text/css" href="/public/css/admin/skin/qingxin/skin.css" id="layout-skin"/>
    <!--页面自定义样式start-->
    <?php if(isset($this->layout['css'])):?>
        <?php if(is_array($this->layout['css'])):?>
            <?php foreach($this->layout['css'] as $css):?>
                <link rel="stylesheet" type="text/css" href="<?php echo $css;?>">
            <?php endforeach;?>
        <?php else:?>
            <link rel="stylesheet" type="text/css" href="<?php echo $this->layout['css'];?>">
        <?php endif;?>
    <?php endif;?>
    <!--页面自定义样式end-->
    <script type="text/javascript" src="/public/js/jquery-2.1.4.min.js"></script>
    <script type="text/javascript" src="/public/admin/js/common/sccl.js"></script>
    <script type="text/javascript" src="/public/admin/js/common/sccl-util.js"></script>
    <!--页面自定义js start-->
    <?php if(isset($this->layout['js'])):?>
        <?php if(is_array($this->layout['js'])):?>
            <?php foreach($this->layout['js'] as $js):?>
            <script src="<?php echo $js;?>" type="text/javascript"></script>
        <?php endforeach;?>
        <?php else:?>
            <script src="<?php echo $this->layout['js'];?>" type="text/javascript"></script>
        <?php endif;?>
    <?php endif;?>
    <!--页面自定义js end-->
</head>

<body>
<div class="layout-admin">
    <header class="layout-header">
        <span class="header-logo">系统框架</span>
        <a class="header-menu-btn" href="javascript:;"><i class="icon-font">&#xe600;</i></a>
        <ul class="header-bar">
            <li class="header-bar-role"><a href="javascript:;">超级管理员</a></li>
            <li class="header-bar-nav">
                <a href="javascript:;">admin<i class="icon-font" style="margin-left:5px;">&#xe60c;</i></a>
                <ul class="header-dropdown-menu">
                    <li><a href="javascript:;">个人信息</a></li>
                    <li><a href="javascript:;">切换账户</a></li>
                    <li><a href="javascript:;">退出</a></li>
                </ul>
            </li>
            <li class="header-bar-nav">
                <a href="javascript:;" title="换肤"><i class="icon-font">&#xe608;</i></a>
                <ul class="header-dropdown-menu right dropdown-skin">
                    <li><a href="javascript:;" data-val="qingxin" title="清新">清新</a></li>
                    <li><a href="javascript:;" data-val="blue" title="蓝色">蓝色</a></li>
                    <li><a href="javascript:;" data-val="molv" title="墨绿">墨绿</a></li>

                </ul>
            </li>
        </ul>
    </header>
    <aside class="layout-side">
        <ul class="side-menu">

        </ul>
    </aside>

    <div class="layout-side-arrow"><div class="layout-side-arrow-icon"><i class="icon-font">&#xe60d;</i></div></div>

    <section class="layout-main">
        <div class="layout-main-tab">
            <button class="tab-btn btn-left"><i class="icon-font">&#xe60e;</i></button>
            <nav class="tab-nav">
                <div class="tab-nav-content">
                    <a href="javascript:;" class="content-tab active" data-id="home.html">首页</a>
                </div>
            </nav>
            <button class="tab-btn btn-right"><i class="icon-font">&#xe60f;</i></button>
        </div>
        <div class="layout-main-body">
            <iframe class="body-iframe" name="iframe0" width="100%" height="99%" src="" frameborder="0" data-id="home.html" seamless></iframe>
        </div>
    </section>
    <div class="layout-footer">@2016 0.1 www.mycodes.net</div>
</div>
</body>
</html>

